### ISSUE TITLE
Unpackerr issues

### ISSUE THREAD

**Issue by bakerboy448** [geekau/media-stack#1]
- Unpackarr does not exist it is Unpackerr
- Unpackerr does not support Whisparr and the configuration is wrong. 
https://github.com/geekau/media-stack/blob/e770cc7a8e4d1787220b7b102f7c26923d03e76b/individual-apps/docker-compose-unpackarr.yaml#L74

Ref https://github.com/davidnewhall/unpackerr/issues/226

**Comment by geekau** [comment]
Updated this a few weeks back, and reverted Whisparr config
